jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
   
workflows:
  version: 2
  build_and_test:
    jobs:
      - build