version: 2
jobs:
  build:
    branches:
      only:
        - master
        
    docker:
      - image: circleci/node:12.13.0

    steps:
      - checkout
      - run: npm install
      - run: npm test